@startuml EstadoEncargado
(*)--> [crearJuego()] Preparado
--> [inicializaThreads()] Trabajando

If "tiempo > 0" then
	--> [tomarLlamada()] Atendiendo
	--> [darPedido()] Dando orden
	--> [cobrar()] Cobrando
	--> Trabajando
else
--> [mostrarDesempeno()] Cerrando
Endif
--> (*)
@enduml